apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-dremio-local
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-data-dremio-local
    namespace: minio-namespace
  hostPath:
    path: /mnt/c/_Rancher/data/dremio/local
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-dremio-local
  namespace: minio-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pv-data-dremio-local
status:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 10Gi
  phase: Bound
  
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-dremio-data
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-data-dremio-data
    namespace: minio-namespace
  hostPath:
    path: /mnt/c/_Rancher/data/dremio/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-dremio-data
  namespace: minio-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pv-data-dremio-data
status:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 10Gi
  phase: Bound
  

---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-dremio-lib
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-data-dremio-lib
    namespace: minio-namespace
  hostPath:
    path: /mnt/c/_Rancher/data/dremio/lib
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-dremio-lib
  namespace: minio-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pv-data-dremio-lib
status:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 10Gi
  phase: Bound