apiVersion: v1
kind: Service
metadata:      
  name: minio-services
  namespace: minio-namespace  
spec:
  ports:
    - name: minio-9000
      nodePort: 30000
      port: 30000
      protocol: TCP
      targetPort: 9000
    - name: minio-9001
      nodePort: 30001
      port: 30001
      protocol: TCP
      targetPort: 9001
  selector:
    app: minio-app
  sessionAffinity: None
  type: NodePort